name: foodly
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  country_picker: ^2.0.23
  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0
  firebase_auth: ^4.15.2
  firebase_core: ^2.32.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_polyline_points: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  flutter_vector_icons: ^2.0.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  glass: ^2.0.0+1
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  lottie: ^3.1.2
  otp_text_field: ^1.1.3
  provider: ^6.1.1
  shimmer: ^3.0.0
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.12.1
  webview_flutter_wkwebview: ^3.9.4

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/anime/
    - assets/icons/
